# check the interpolation with the csvs from James

In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import cmocean
import matplotlib.dates as mdates
from matplotlib.lines import Line2D
# import datetime.datetime as datetime

In [2]:
# load the flux time series for each scenario
base=pd.read_csv('/global/scratch/users/jennaisrael/BayDeltaSCHISM/data/time_history/flux.th',sep=r'\s+',parse_dates=["datetime"],dtype=np.float32).set_index(["datetime"])
dcp=pd.read_csv('/global/scratch/users/jennaisrael/scenario_files/DCP/data/time_history/flux_dcp_fixinterp.th.ported',sep=r'\s+',parse_dates=["datetime"],dtype=np.float32).set_index(["datetime"])
cor=pd.read_csv('/global/scratch/users/jennaisrael/scenario_files/reserves/data/time_history/flux_cor_fixinterp.th.ported',sep=r'\s+',parse_dates=["datetime"],dtype=np.float32).set_index(["datetime"])
base

,coyote,ccc_rock,ccc_old,swp,cvp,sjr,calaveras,east,american,sac,yolo_toedrain,yolo,northbay,napa,ccc_victoria
datetime,,,,,,,,,,,,,,,
2006-10-01 00:00:00,-0.62,0.67,4.52,262.320007,120.830002,-94.860001,-0.0,-25.780001,-72.769997,-330.570007,0.68,-0.00,2.48,-0.01,0.0
2006-10-01 00:15:00,-0.62,0.67,4.52,263.239990,120.820000,-94.860001,-0.0,-25.730000,-71.919998,-330.640015,-4.62,-0.00,2.46,-0.01,0.0
2006-10-01 00:30:00,-0.62,0.66,4.52,263.410004,120.820000,-95.430000,-0.0,-25.690001,-73.339996,-331.000000,-8.10,-0.00,2.46,-0.01,0.0
2006-10-01 00:45:00,-0.62,0.66,4.52,263.390015,120.820000,-94.860001,-0.0,-25.660000,-73.910004,-331.070007,-9.66,-0.00,2.45,-0.01,0.0
2006-10-01 01:00:00,-0.62,0.66,4.52,263.350006,120.820000,-94.860001,-0.0,-25.629999,-73.910004,-331.420013,-10.65,-0.00,2.45,-0.01,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-05-13 23:00:00,-0.84,2.46,4.18,1.680000,24.850000,-179.250000,-0.0,-63.320000,-116.379997,-749.340027,0.06,-0.01,1.55,-1.68,0.0
2024-05-13 23:15:00,-0.84,2.44,4.22,1.700000,24.719999,-180.100006,-0.0,-63.450001,-115.820000,-749.340027,0.06,-0.01,1.55,-1.65,0.0
2024-05-13 23:30:00,-0.84,2.41,4.27,1.720000,24.570000,-179.529999,-0.0,-63.360001,-116.379997,-749.340027,0.06,-0.01,1.55,-1.65,0.0
2024-05-13 23:45:00,-0.84,2.39,4.33,1.770000,24.389999,-180.380005,-0.0,-63.500000,-116.379997,-749.340027,0.06,-0.01,1.55,-1.65,0.0
2024-05-14 00:00:00,-0.84,2.35,4.40,1.840000,24.180000,-180.100006,-0.0,-63.639999,-117.510002,-749.340027,0.06,-0.01,1.54,-1.65,0.0

In [27]:
rawdcp=pd.read_csv('/global/scratch/users/jennaisrael/scenario_files/DCP/s0065_DWRadapt25_2020LU_DCP_DV_v01_20260119_morevars.csv',
                  skiprows=1).loc[5:]
rawdcp
rawdcp['datetime']=pd.to_datetime(rawdcp.B,format="%Y-%m-%d")
rawdcp.set_index(["datetime"],inplace=True)
rawdcp=rawdcp.drop(columns=["B"]).astype(np.float32)
rawcor=pd.read_csv('/global/scratch/users/jennaisrael/scenario_files/reserves/s0044_DCRadjHist_2020LU_ShastaCarryover20_DV_v0.1_20251211_morevars.csv',
                   skiprows=1).loc[5:]
rawcor['datetime']=pd.to_datetime(rawcor.B,format="%Y-%m-%d")
rawcor.set_index(["datetime"],inplace=True)
rawcor=rawcor.drop(columns=["B"]).astype(np.float32)
rawcor

,AWOANN_64_XADV,AWOANN_72_XA1DV,AWOANN_72_XA2DV,AWOANN_72_XA3DV,AWOANN_73_XADV,BANKSEC_MAX14DAY,COREQSACDV,CO_EC_MONTH,C_AMR004,C_AMR004_ADD,...,S_SLTOT,D_TOTAL,S_RESTOT,S_RESTOT_NOD,DEL_CVP_TOTAL,DEL_CVPSWP_TOTAL,DEL_CVP_PAG_TOTAL,DEL_CVP_PSCEX_TOTAL,DEL_CVP_PRF_TOTAL,AWOANN_ALL_DV
datetime,,,,,,,,,,,,,,,,,,,,,
1921-10-31,52.155048,117.461761,206.691589,265.654022,65.766907,284.734375,0.000000,2173.848877,2908.896973,2408.896973,...,602.326050,3666.807129,9308.182617,7641.695801,6360.680176,10366.100586,2665.407227,1825.189087,1535.394775,707.729309
1921-11-30,52.155048,117.461761,206.691589,265.654022,65.766907,273.095795,0.000000,2616.461182,1881.908569,1381.908569,...,678.799683,8969.550781,9035.086914,7348.482422,1385.989136,2270.764648,264.171997,231.576294,535.016235,707.729309
1921-12-31,52.155048,117.461761,206.691589,265.654022,65.766907,376.717224,4819.347168,5862.487305,2033.443970,1533.443970,...,1086.051758,11972.789062,9403.040039,7648.825195,1228.581421,2128.262207,513.112732,92.837738,281.697754,707.729309
1922-01-31,52.155048,117.461761,206.691589,265.654022,65.766907,643.843262,0.000000,10944.633789,1709.546265,1459.546265,...,1432.604370,7256.958008,9661.392578,7803.534668,1171.003784,1778.431396,344.563843,243.720840,292.222626,707.729309
1922-02-28,52.155048,117.461761,206.691589,265.654022,65.766907,416.905090,0.000000,2758.712158,6534.421875,6284.421875,...,1876.645142,9128.436523,10642.616211,8596.959961,525.726318,634.710022,0.000000,34.635178,284.266327,707.729309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-31,61.750805,138.517532,241.319199,308.273102,76.776810,386.525421,0.000000,4020.551514,608.698730,343.905518,...,815.587341,2260.674805,7639.644531,5852.898926,7266.125000,8765.191406,209.039108,6445.623047,169.714630,826.637390
2021-06-30,61.750805,138.517532,241.319199,308.273102,76.776810,385.203918,0.000000,6620.244141,2125.206055,1860.412964,...,673.880798,1100.000000,6911.955078,5249.312500,7558.288086,9433.183594,160.021881,6656.186523,98.425987,826.637390
2021-07-31,61.750805,138.517532,241.319199,308.273102,76.776810,505.178680,0.000000,9112.302734,2067.896729,1803.103516,...,497.872864,1427.000000,6012.955078,4456.731445,8423.513672,10652.178711,150.127945,7448.446289,111.242325,826.637390
2021-08-31,61.750805,138.517532,241.319199,308.273102,76.776810,560.294495,0.000000,10266.850586,3170.156982,2905.363770,...,363.768005,1430.000000,5353.403809,3863.166504,6202.635742,7747.439941,108.752701,5237.601074,226.487198,826.637390
2021-09-30,61.750805,138.517532,241.319199,308.273102,76.776810,515.416077,0.000000,10104.483398,365.873260,8.080048,...,289.846100,1500.000000,5154.612305,3642.740967,3633.052734,4493.970703,58.631851,2576.728760,647.705872,826.637390

In [28]:
rawdcp.C_SAC041[0]

14130.295

In [23]:
np.nanmean(dcp.sac/(dcp.sac+dcp.american))

0.83809525

In [29]:
rawdcp['sac']=np.nanmean(dcp.sac/(dcp.sac+dcp.american)) * (rawdcp.C_SAC041)

In [ ]:
# make stacked plots 
fig, ax = plt.subplots(1,figsize=(15,10),sharex=True,layout='constrained')
mpl.rcParams.update({'font.size': 22})

# ax[0].plot(base.net,label='Baseline', linewidth=3,color=cmocean.cm.tarn(1/6))
# ax[0].plot(dcp.net,label='DCP', linewidth=3,color=cmocean.cm.tarn(10/12))
# ax[0].plot(cor.net,label='CoR', linewidth=3,color=cmocean.cm.tarn(2/6))
# ax[0].set_title('Inflows - Exports')
# ax[0].set_ylabel(r'Flow [$m^3 s^{-1}$]')
# ax[0].set_xlim(pd.to_datetime("2018-10-1"),pd.to_datetime("2019-9-30"))
# ax[0].set_ylim(0,5000)
# ax[0].legend(bbox_to_anchor=(1.05, 1),
#                          loc='upper left', borderaxespad=0.)

# ax[0].plot(base.inf, linewidth=3,label='Total inflows',color=cmocean.cm.tarn(1/6))
# ax[0].plot(dcp.inf, linewidth=3,color=cmocean.cm.tarn(10/12))
# ax[0].plot(cor.inf, linewidth=3,color=cmocean.cm.tarn(2/6))

ax[0].plot(base.sac*-1, linewidth=3,label='Sacramento river',color=cmocean.cm.tarn(1/6),linestyle='--')
ax[0].plot(dcp.sac*-1, linewidth=3,color=cmocean.cm.tarn(10/12),linestyle='--')
ax[0].plot(cor.sac*-1, linewidth=3,color=cmocean.cm.tarn(2/6),linestyle='--')

ax[0].plot(base.sac*-1, linewidth=3,label='Sacramento river',color=cmocean.cm.tarn(1/6),linestyle='--')
ax[0].plot(dcp.sac*-1, linewidth=3,color=cmocean.cm.tarn(10/12),linestyle='--')
ax[0].plot(cor.sac*-1, linewidth=3,color=cmocean.cm.tarn(2/6),linestyle='--')

# ax[1].plot(base.sjr*-1, linewidth=3,label='San Joaquin river',color=cmocean.cm.tarn(1/6),linestyle=(0,(1,1)))
# ax[1].plot(dcp.sjr*-1, linewidth=3,color=cmocean.cm.tarn(10/12),linestyle=(0,(1,1)))
# ax[1].plot(cor.sjr*-1, linewidth=3,color=cmocean.cm.tarn(2/6),linestyle=(0,(1,1)))

# ax[1].plot(base.yolo*-1, linewidth=3,label='Yolo bypass',color=cmocean.cm.tarn(1/6),linestyle=(0,(1,1)))
# ax[1].plot(dcp.yolo*-1, linewidth=3,color=cmocean.cm.tarn(10/12),linestyle=(0,(1,1)))
# # ax[1].plot(cor.yolo*-1, linewidth=3,color=cmocean.cm.tarn(2/6),linestyle=(0,(1,1)))

ax[1].legend(bbox_to_anchor=(1.05, 1),
                         loc='upper left', borderaxespad=0.)
ax[1].set_title('Inflows')
ax[1].set_ylabel(r'Flow [$m^3 s^{-1}$]')
ax[1].set_xlim(pd.to_datetime("2018-10-1"),pd.to_datetime("2019-9-30"))
ax[1].set_ylim(0,5000)

ax[2].plot(base.exports, linewidth=3,color=cmocean.cm.tarn(1/6))
ax[2].plot(dcp.exports, linewidth=3,color=cmocean.cm.tarn(10/12),label='Total exports')
ax[2].plot(cor.exports, linewidth=3,color=cmocean.cm.tarn(2/6))

ax[2].plot(tunnel, linewidth=3,linestyle=(0,(1,1)),label='N. Delta exports',color=cmocean.cm.tarn(10/12))

ax[2].plot(base.s_exports, linewidth=3,color=cmocean.cm.tarn(1/6),linestyle='--')
ax[2].plot(dcp.s_exports, linewidth=3,color=cmocean.cm.tarn(10/12),linestyle='--',label='S. Delta exports')
ax[2].plot(cor.s_exports, linewidth=3,color=cmocean.cm.tarn(2/6),linestyle='--')

ax[2].legend(bbox_to_anchor=(1.05, 1),
                         loc='upper left', borderaxespad=0.)
ax[2].set_title('Exports')
ax[2].set_ylabel(r'Flow [$m^3 s^{-1}$]')
ax[2].set_xlim(pd.to_datetime("2018-10-1"),pd.to_datetime("2021-9-30"))
ax[2].set_ylim(0,500)

ax[2].xaxis.set_major_formatter(mdates.ConciseDateFormatter(ax[2].xaxis.get_major_locator()))
ax[2].xaxis.set_major_formatter(mdates.DateFormatter('%Y-%b-%d'))
    # Rotates and right-aligns the x labels so they don't crowd each other.
for label in ax[2].get_xticklabels(which='major'):
    label.set(rotation=30, horizontalalignment='right')

#fig.savefig('/home/jisrael/Savio_scratch_back_up/Plotting/expanse/ch_3_figures/inflows_exports_scenarios_trim_feb.png')