In [1]:
from bdschism.ccf_gate_height import ccf_gate, sffpx_level
import os

In [2]:
model_start = "2018-08-14"
model_end = "2021-10-01"

dated_case_dir="/home/jisrael/BayDeltaSCHISM/data/time_history/"
export_file = os.path.join(dated_case_dir, "flux.th")
#Lily sent me the astro_file
astro_file = "/home/jisrael/Savio_scratch_back_up/scripts/preprocessing_scripts/oh4_15min_predicted_10y_01_25.out" #"/scratch/projects/dsp/updated_schism_202602/th_files/prepro_files/oh4_15min_predicted_10y_01_25.out"
sf_data_repo = "/expanse/lustre/scratch/jisrael/temp_project/validation_data/screened/" #"/scratch/nasbdo/modeling_data/repo/continuous/screened/"
plot = False

In [3]:
sffpx_elev=sffpx_level(
      model_start,
      model_end,
      sf_data_repo,
)
# ccf_gate(
#       model_start,
#       model_end,
#       "./ccfb_gate_dated.th",
#       astro_file,
#       export_file,
#       sffpx_elev,
#       plot,
# )

85
Empty DataFrame
Columns: [value]
Index: []

In [4]:
sffpx_elev

Empty DataFrame
Columns: [value]
Index: []

In [ ]:
flag

In [7]:
from dms_datastore.read_multi import read_ts_repo, infer_source_priority

In [6]:
read_ts_repo("sffpx", "elev", repo=sf_data_repo, src_priority="infer")

Empty DataFrame
Columns: [value]
Index: []

In [10]:
read_ts_repo("sffpx", "elev", repo=sf_data_repo, src_priority="infer",start=model_start, end=model_end)

                     value
2018-08-14 00:00:00  1.847
2018-08-14 00:06:00  1.864
2018-08-14 00:12:00  1.883
2018-08-14 00:18:00  1.896
2018-08-14 00:24:00  1.923
...                    ...
2021-09-30 23:36:00  0.362
2021-09-30 23:42:00  0.335
2021-09-30 23:48:00  0.314
2021-09-30 23:54:00  0.301
2021-10-01 00:00:00  0.282

[274561 rows x 1 columns]

In [9]:
infer_source_priority("sffpx")

['noaa']